#this is a github actions workflow file
name: ShellScriptUtils - preparing artifact file
run-name: $${{ github.author }} is preparing a file for release (or upload)
on:
  workflow_call:
    inputs:
      destination-filename:
        required: true
        type: string
      
jobs:
  preparing-artifact-file:
    name: preparing artifact file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: saving files to a tar.gz
        #run tar -czf, excluding .git and .github folders
        run: |
          currentFolderName=${PWD##*/}
          cd ..
          ls -lha
          echo "coping files for a new folder"
          echo "reponame: $currentFolderName"
          echo "destination-filename: ${{ inputs.destination-filename }}"
          cp -r "$currentFolderName" ${{ inputs.destination-filename }}
          rm -rf ${{ inputs.destination-filename }}/.git
          rm -rf ${{ inputs.destination-filename }}/.github
          
          echo "Packing the folder ${{ inputs.destination-filename }}  (excluding .githuba and .git folders) ..."
          tar -czf ${{ inputs.destination-filename }}.tar.gz ${{ inputs.destination-filename }}
