#this is a github actions workflow file
name: ShellScriptUtils - default CI
run-name: ${{ github.author }} is running the CI
on:
  push:
    branches:
      - main
      - develop
jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/runtests.yaml
    with:
      tests-folder: tests
      main-script: runtests.sh

    