#this is a github actions workflow file
name: ShellScriptUtils - default CI
run-name: ${{ github.author }} is running the CI
on:
  push:
    branches:
      - main
      - develop
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y bc

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Running tests
        run: |
          echo "Running tests..."
          cd tests
          chmod +x ./runtests.sh
          ./runtests.sh

    