#this is a github actions workflow file
name: ShellScriptUtils - default CI
run-name: ${{ github.author }} is running the CI
on:
  push:
    branches:
      - main
      - develop
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          #check if sudo is installed
          if ! [ -x "$(command -v sudo)" ]; then
            echo "sudo is not installed. Installing sudo..."
            apt update -y > /dev/null 2>&1
            apt install sudo -y
            sudo apt update -y
            sudo apt install -y bc
          fi
          sudo apt update -y
          sudo apt install -y bc

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Running tests
        run: |
          echo "Running tests..."
          cd tests
          chmod +x ./runtests.sh
          ./runtests.sh

    